project:
  type: website
  output-dir: docs
  resources:
    "posts/assets/**"

execute:
  freeze: false

website:
  title: "SegfaultDSP"
  navbar:
    right:
      - icon: github
        href: https://github.com/segfault1602
format:
  html:
    theme: flatly
    css: styles.css