project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: true
  resources:
    "posts/assets/**"

execute:
  freeze: false

website:
  title: "SegfaultDSP"
  reader-mode: true
  favicon: "favicon.svg"
  navbar:
    right:
      - icon: github
        href: https://github.com/segfault1602
  sidebar:
    style: "docked"
    search: true
    contents: auto
  google-analytics:
    tracking-id: "G-210NT6BWYX"
    anonymize-ip: true
    storage: none

format:
  html:
    theme: flatly
    css: styles.css