project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: true
  resources:
    "posts/assets/**"

execute:
  freeze: false

website:
  title: "SegfaultDSP"
  navbar:
    right:
      - icon: github
        href: https://github.com/segfault1602
  sidebar:
    style: "docked"
    search: true
    contents: auto

format:
  html:
    theme: flatly
    css: styles.css