---
title: "BowedString Part 3: BowedString audio example"
date: '2023-09-16'
jupyter: python3
---

Here are a few audio examples of the BowedString instrument in its current state. As a reminder, what we have right now is a digital waveguide with a nut and bridge. The bridge has a slight low-pass filter. The string is excited by the bow model we discussed in [part 2](../bow_table/bow_table.qmd).

If these sound cold and robotic, that is to be expected. The body filter is missing and all of these samples were generated by C++ code with all of the parameters moving in a perfectly linear way. It is helpful to have simple and easily reproducible sounds to test the code with and will make debugging and tuning the instrument much easier.

1. Velocity and Force sweep from 0 to 1 then back to 0.

<html>
<audio controls>
  <source src="../assets/velocity_sweep.wav" type="audio/wav">
</audio></html>

---

2. Fast bowing by modulating velocity with a clipped sine wave. A staccato sound can be achieved by reducing the amount of clipping.

<html>
<audio controls>
  <source src="../assets/fast_note.wav" type="audio/wav">
</audio></html>

---

3. Vibrato. The length of the string is modulated by a sine wave.

<html>
<audio controls>
  <source src="../assets/vibrato.wav" type="audio/wav">
</audio></html>

---

4. Pitch slide, 440Hz to 660Hz.

<html>
<audio controls>
  <source src="../assets/pitchslide.wav" type="audio/wav">
</audio></html>
